### Create Cash Holding Account
POST http://0.0.0.0:8000/api/v1/bank-accounts
Content-Type: application/json

{
  "owner_id": 1,
  "balance": 120000.00,
  "account_type": "ADMINISTRATIVE",
  "status": "ACTIVE"
}

### Create Cash Disbursement Account
POST http://0.0.0.0:8000/api/v1/bank-accounts
Content-Type: application/json

{
  "owner_id": 1,
  "balance": 120000.00,
  "account_type": "ADMINISTRATIVE",
  "status": "ACTIVE"
}

### Create Cash Disbursement Account
POST http://0.0.0.0:8000/api/v1/bank-accounts
Content-Type: application/json

{
  "owner_id": 1,
  "account_number": "Normal Bank",
  "balance": 122.00,
  "account_type": "USER",
  "status": "ACTIVE"
}

### Get all bank accounts
GET http://0.0.0.0:8000/api/v1/bank-accounts

