### Create Cash Holding Account
POST http://0.0.0.0:8000/api/v1/accounts
Content-Type: application/json

{
  "account_number": "CASH_HOLD",
  "balance": 10000.00,
  "account_type": "ADMINISTRATIVE",
  "status": "ACTIVE"
}

### Create Cash Disbursement Account
POST http://0.0.0.0:8000/api/v1/accounts
Content-Type: application/json

{
  "account_number": "CASH_DISBURSE",
  "balance": 5000.00,
  "type": "ADMINISTRATIVE",
  "status": "ACTIVE"
}